In [17]:
'''write a python programm to an array and perform additon of two matrices.(using list and numpy array)'''
import numpy as ds

A = ds.array([[1, 2, 3],[4, 5, 6]])

B = ds.array([[7, 8, 9],[10, 11, 12]])

C = ds.array([[0, 1, 3],[14, 15, 22]])

#adding two matrices
M = A + B

N = B + C

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of A and B:")
print(M)

print("\nAddition of C and B:")
print(N)



Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition of A and B:
[[ 8 10 12]
 [14 16 18]]

Addition of C and B:
[[ 7  9 12]
 [24 26 34]]
